language: cpp

matrix:
  include:
    # We need c++ 17 support, travis defaults to gcc 4.8. We want gcc 7 (or newer)
    - name: "Linux Build"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

    # Windows requires VS 2017 15.7 or higher, this is installed by default on travis
    - name: "Windows Build"
      os: windows


    # Run linters
    - name: "Code Style"
      os: linux
      language: bash
      script:
        - $TRAVIS_BUILD_DIR/tools/check_code_style.sh

script:
  - mkdir -p $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..
  - cmake --build .
  - $TRAVIS_BUILD_DIR/bin/unit-tests

notifications:
  email:
    on_success: never
    on_failure: never
