language: cpp

# By default travis uses gcc 4.8.4 which doesn't fully support c++11
# Lets manually install the correct versions (and also test against multiple
# versions)
# See: https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux
matrix:
  include:
    # Old gcc versions disabled, as lead to ambiguity with xen::startsWith()
    # and xen::endsWith, see: https://travis-ci.org/jnterry/xeno-engine/jobs/428258853
    #- os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-4.9
    #  env:
    #     - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    #- os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-5
    #  env:
    #     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    #- os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-6
    #  env:
    #    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - g++ --version
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake .. && make
  - cd $TRAVIS_BUILD_DIR/bin && ./unit-tests


notifications:
  email:
    on_success: never
    on_failure: never
