language: cpp

matrix:
  include:
    # We need c++ 17 support, travis defaults to gcc 4.8. We want gcc 7 (or newer)
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:

    # We can also test on windows with VS 2017
    - os: windows

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..
  - cmake --build .
  - $TRAVIS_BUILD_DIR/bin/unit-tests
  - $TRAVIS_BUILD_DIR/tools/check_code_style.sh


notifications:
  email:
    on_success: never
    on_failure: never
