language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
script:
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake .. && make
  - cd $TRAVIS_BUILD_DIR/bin && ./unit-tests
notifications:
  email:
    on_success: never
    on_failure: never
